[versions]
guava = "33.1.0-jre"
junit-bom = "5.10.0"
picocli = "4.7.6"
jackson-databind = "2.15.2"
jackson-dataformat-yaml = "2.14.1"

[libraries]
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-bom" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-databind" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jackson-dataformat-yaml" }